### ISSUE TITLE
Підтвердження після реєстрації тварини

### ISSUE THREAD

**Issue by yra1908** [if-056-java/animalsRepo#109]
Неясно чи тварина зареєстрована після заповнення форми. Потрібно якись меседж - невдала спроба чи успішно зареєстровано. Зараз доводиться дивитися в консоль

**Comment by yra1908** [comment]
можна дати редірект на сторінку детальної інформації про тварину

**Comment by OlegSvyryd** [comment]
якраз за це сідав)
