### ISSUE TITLE
Реєстрація власної тварини. Баг з полем стать

### ISSUE THREAD

**Issue by yra1908** [if-056-java/animalsRepo#120]
Поле стать є обовязкове але реєстрація дозволяється при невказаному полі(валідація на ангуларі) Також необробляється випадок невдалого реквесту - при бед реквесті все одно появляється підтвердження реєстрації і перенаправляє у власний кабінет.

**Comment by OlegSvyryd** [comment]
про обов'язковість пофіксив, хендили екзепшини буду після узгодження даної с-ми
