### ISSUE TITLE
Форма "Мій кабінет" - івент на кнопки при редагуванні користувача

### ISSUE THREAD

**Issue by TymYur** [if-056-java/animalsRepo#52]
На копки "Зберегти" та "Відмінити" повішено 1-ин і той-же івент - ng-click="closePopup()", який завжди відсилає на REST зміненого користувача.
Повинна на кнопці "Відмінити" висіти "пуста" подія - нічого не відсилає.

**Comment by TymYur** [comment]
![image](https://cloud.githubusercontent.com/assets/13005331/9490259/68620306-4bef-11e5-8af8-439487d7be45.png)

**Comment by yra1908** [comment]
Там трохи не така проблема була. При скасувати не відсилався рест. Просто на сторінці мінялося поточне значення scope. Частково виправив. Буду думати як поміняти взагалі логіку на цій сторінці
