### ISSUE TITLE
баг при телефонному розмірі екрана

### ISSUE THREAD

**Issue by OlegSvyryd** [if-056-java/animalsRepo#88]
сидів через тел, там коли клікаєш на цей список прихований, він відкривається, переходиш на потрібну сторінку, воно тебе норм редіректить і на тій сторінці залишається відкритий цей список, треба шоб закривався, і вобше, шось не дуже з телефона грузить..

**Comment by TymYur** [comment]
data-toggle="collapse" data-target=".navbar-collapse"
