### ISSUE TITLE
на сторінці профіль при кліці на кнопку add own animal пише замало інфи, відредагуйте профіль, при натисненні на хедері registration own animal - дозволяє додати..

### ISSUE THREAD

**Issue by OlegSvyryd** [if-056-java/animalsRepo#94]

**Comment by yra1908** [comment]
Є таке. Найпростіше буде забрати це обмеження. На сторінці профіля я беру
дані з scope в якому є user. Для обмеження на кнопку reg own animal -
незнаю звідки брати дані...

**Comment by OlegSvyryd** [comment]
fixed?

**Comment by yra1908** [comment]
я забрав ці обмеження. може редагувати будь-який зареєстрований користувач. навіть без контактної інформації
